apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec: 
  selector:
    matchLabels: 
      app: product-service
  replicas: 1
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: florinpana01/tradetreasure-product-service-repository
          ports:
            - containerPort: 8002
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: product-service-db-secret
                  key: productname
            - name: DB_PASS
              valueFrom: 
                secretKeyRef:
                  name: product-service-db-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: product-service-db-secret
                  key: database
